export const ADD_BRAND: 'ADD_BRAND' = 'ADD_BRAND';
export const ADD_BRAND_SUCCEED: 'ADD_BRAND_SUCCEED' = 'ADD_BRAND_SUCCEED';
export const ADD_BRAND_FAILED: 'ADD_BRAND_FAILED' = 'ADD_BRAND_FAILED';

export const ADD_MODEL: 'ADD_MODEL' = 'ADD_MODEL';
export const ADD_MODEL_SUCCEED: 'ADD_MODEL_SUCCEED' = 'ADD_MODEL_SUCCEED';
export const ADD_MODEL_FAILED: 'ADD_MODEL_FAILED' = 'ADD_MODEL_FAILED';

export const ASSOCIATE_MODEL_BRAND: 'ASSOCIATE_MODEL_BRAND' = 'ASSOCIATE_MODEL_BRAND';
export const ASSOCIATE_MODEL_BRAND_SUCCEED: 'ASSOCIATE_MODEL_BRAND_SUCCEED' = 'ASSOCIATE_MODEL_BRAND_SUCCEED';
export const ASSOCIATE_MODEL_BRAND_FAILED: 'ASSOCIATE_MODEL_BRAND_FAILED' = 'ASSOCIATE_MODEL_BRAND_FAILED';

export const GET_BRANDS: 'GET_BRANDS' = 'GET_BRANDS';
export const GET_BRANDS_SUCCEED: 'GET_BRANDS_SUCCEED' = 'GET_BRANDS_SUCCEED';
export const GET_BRANDS_FAILED: 'GET_BRANDS_FAILED' = 'GET_BRANDS_FAILED';

export const GET_MODELS_WITHOUT_BRAND: 'GET_MODELS' = 'GET_MODELS';
export const GET_MODELS_WITHOUT_BRAND_SUCCEED: 'GET_MODELS_SUCCEED' = 'GET_MODELS_SUCCEED';
export const GET_MODELS_WITHOUT_BRAND_FAILED: 'GET_MODELS_FAILED' = 'GET_MODELS_FAILED';

export const GET_DRIVES: 'GET_DRIVES' = 'GET_DRIVES';
export const GET_DRIVES_SUCCEED: 'GET_DRIVES_SUCCEED' = 'GET_DRIVES_SUCCEED';
export const GET_DRIVES_FAILED: 'GET_DRIVES_FAILED' = 'GET_DRIVES_FAILED';

export const ADD_DRIVE: 'ADD_DRIVE' = 'ADD_DRIVE';
export const ADD_DRIVE_SUCCEED: 'ADD_DRIVE_SUCCEED' = 'ADD_DRIVE_SUCCEED';
export const ADD_DRIVE_FAILED: 'ADD_DRIVE_FAILED' = 'ADD_DRIVE_FAILED';

export const UPDATE_DRIVE: 'UPDATE_DRIVE' = 'UPDATE_DRIVE';
export const UPDATE_DRIVE_SUCCEED: 'UPDATE_DRIVE_SUCCEED' = 'UPDATE_DRIVE_SUCCEED';
export const UPDATE_DRIVE_FAILED: 'UPDATE_DRIVE_FAILED' = 'UPDATE_DRIVE_FAILED';

export const DELETE_DRIVE: 'DELETE_DRIVE' = 'DELETE_DRIVE';
export const DELETE_DRIVE_SUCCEED: 'DELETE_DRIVE_SUCCEED' = 'DELETE_DRIVE_SUCCEED';
export const DELETE_DRIVE_FAILED: 'DELETE_DRIVE_FAILED' = 'DELETE_DRIVE_FAILED';


export const ADD_ENGINE: 'ADD_ENGINE' = 'ADD_ENGINE';
export const ADD_ENGINE_SUCCEED: 'ADD_ENGINE_SUCCEED' = 'ADD_ENGINE_SUCCEED';
export const ADD_ENGINE_FAILED: 'ADD_ENGINE_FAILED' = 'ADD_ENGINE_FAILED';

export const UPDATE_ENGINE: 'UPDATE_ENGINE' = 'UPDATE_ENGINE';
export const UPDATE_ENGINE_SUCCEED: 'UPDATE_ENGINE_SUCCEED' = 'UPDATE_ENGINE_SUCCEED';
export const UPDATE_ENGINE_FAILED: 'UPDATE_ENGINE_FAILED' = 'UPDATE_ENGINE_FAILED';

export const DELETE_ENGINE: 'DELETE_ENGINE' = 'DELETE_ENGINE';
export const DELETE_ENGINE_SUCCEED: 'DELETE_ENGINE_SUCCEED' = 'DELETE_ENGINE_SUCCEED';
export const DELETE_ENGINE_FAILED: 'DELETE_ENGINE_FAILED' = 'DELETE_ENGINE_FAILED';

export const GET_ENGINES: 'GET_ENGINES' = 'GET_ENGINES';
export const GET_ENGINES_SUCCEED: 'GET_ENGINES_SUCCEED' = 'GET_ENGINES_SUCCEED';
export const GET_ENGINES_FAILED: 'GET_ENGINES_FAILED' = 'GET_ENGINES_FAILED';

export const GET_BODY_TYPES: 'GET_BODY_TYPES' = 'GET_BODY_TYPES';
export const GET_BODY_TYPES_SUCCEED: 'GET_BODY_TYPES_SUCCEED' = 'GET_BODY_TYPES_SUCCEED';
export const GET_BODY_TYPES_FAILED: 'GET_BODY_TYPES_FAILED' = 'GET_BODY_TYPES_FAILED';

export const GET_TRANSMISSIONS: 'GET_TRANSMISSIONS' = 'GET_TRANSMISSIONS';
export const GET_TRANSMISSIONS_SUCCEED: 'GET_TRANSMISSIONS_SUCCEED' = 'GET_TRANSMISSIONS_SUCCEED';
export const GET_TRANSMISSIONS_FAILED: 'GET_TRANSMISSIONS_FAILED' = 'GET_TRANSMISSIONS_FAILED';

export const GET_COLORS: 'GET_COLORS' = 'GET_COLORS';
export const GET_COLORS_SUCCEED: 'GET_COLORS_SUCCEED' = 'GET_COLORS_SUCCEED';
export const GET_COLORS_FAILED: 'GET_COLORS_FAILED' = 'GET_COLORS_FAILED';


export const ADD_BODY_TYPE: 'ADD_BODY_TYPE' = 'ADD_BODY_TYPE';
export const ADD_BODY_TYPE_SUCCEED: 'ADD_BODY_TYPE_SUCCEED' = 'ADD_BODY_TYPE_SUCCEED';
export const ADD_BODY_TYPE_FAILED: 'ADD_BODY_TYPE_FAILED' = 'ADD_BODY_TYPE_FAILED';

export const UPDATE_BODY_TYPE: 'UPDATE_BODY_TYPE' = 'UPDATE_BODY_TYPE';
export const UPDATE_BODY_TYPE_SUCCEED: 'UPDATE_BODY_TYPE_SUCCEED' = 'UPDATE_BODY_TYPE_SUCCEED';
export const UPDATE_BODY_TYPE_FAILED: 'UPDATE_BODY_TYPE_FAILED' = 'UPDATE_BODY_TYPE_FAILED';

export const DELETE_BODY_TYPE: 'DELETE_BODY_TYPE' = 'DELETE_BODY_TYPE';
export const DELETE_BODY_TYPE_SUCCEED: 'DELETE_BODY_TYPE_SUCCEED' = 'DELETE_BODY_TYPE_SUCCEED';
export const DELETE_BODY_TYPE_FAILED: 'DELETE_BODY_TYPE_FAILED' = 'DELETE_BODY_TYPE_FAILED';

export const ADD_TRANSMISSION: 'ADD_TRANSMISSION' = 'ADD_TRANSMISSION';
export const ADD_TRANSMISSION_SUCCEED: 'ADD_TRANSMISSION_SUCCEED' = 'ADD_TRANSMISSION_SUCCEED';
export const ADD_TRANSMISSION_FAILED: 'ADD_TRANSMISSION_FAILED' = 'ADD_TRANSMISSION_FAILED';

export const UPDATE_TRANSMISSION: 'UPDATE_TRANSMISSION' = 'UPDATE_TRANSMISSION';
export const UPDATE_TRANSMISSION_SUCCEED: 'UPDATE_TRANSMISSION_SUCCEED' = 'UPDATE_TRANSMISSION_SUCCEED';
export const UPDATE_TRANSMISSION_FAILED: 'UPDATE_TRANSMISSION_FAILED' = 'UPDATE_TRANSMISSION_FAILED';

export const DELETE_TRANSMISSION: 'DELETE_TRANSMISSION' = 'DELETE_TRANSMISSION';
export const DELETE_TRANSMISSION_SUCCEED: 'DELETE_TRANSMISSION_SUCCEED' = 'DELETE_TRANSMISSION_SUCCEED';
export const DELETE_TRANSMISSION_FAILED: 'DELETE_TRANSMISSION_FAILED' = 'DELETE_TRANSMISSION_FAILED';

export const ADD_COLOR: 'ADD_COLOR' = 'ADD_COLOR';
export const ADD_COLOR_SUCCEED: 'ADD_COLOR_SUCCEED' = 'ADD_COLOR_SUCCEED';
export const ADD_COLOR_FAILED: 'ADD_COLOR_FAILED' = 'ADD_COLOR_FAILED';

export const UPDATE_COLOR: 'UPDATE_COLOR' = 'UPDATE_COLOR';
export const UPDATE_COLOR_SUCCEED: 'UPDATE_COLOR_SUCCEED' = 'UPDATE_COLOR_SUCCEED';
export const UPDATE_COLOR_FAILED: 'UPDATE_COLOR_FAILED' = 'UPDATE_COLOR_FAILED';

export const DELETE_COLOR: 'DELETE_COLOR' = 'DELETE_COLOR';
export const DELETE_COLOR_SUCCEED: 'DELETE_COLOR_SUCCEED' = 'DELETE_COLOR_SUCCEED';
export const DELETE_COLOR_FAILED: 'DELETE_COLOR_FAILED' = 'DELETE_COLOR_FAILED';


export const GET_MODELS_BY_BRAND: 'GET_MODELS_BY_BRAND' = 'GET_MODELS_BY_BRAND';
export const GET_MODELS_BY_BRAND_SUCCEED: 'GET_MODELS_BY_BRAND_SUCCEED' = 'GET_MODELS_BY_BRAND_SUCCEED';
export const GET_MODELS_BY_BRAND_FAILED: 'GET_MODELS_BY_BRAND_FAILED' = 'GET_MODELS_BY_BRAND_FAILED';

export const ADD_MODEL_ENGINE_ASSOCIATION: 'ADD_MODEL_ENGINE_ASSOCIATION' = 'ADD_MODEL_ENGINE_ASSOCIATION';
export const ADD_MODEL_ENGINE_ASSOCIATION_SUCCEED: 'ADD_MODEL_ENGINE_ASSOCIATION_SUCCEED' = 'ADD_MODEL_ENGINE_ASSOCIATION_SUCCEED';
export const ADD_MODEL_ENGINE_ASSOCIATION_FAILED: 'ADD_MODEL_ENGINE_ASSOCIATION_FAILED' = 'ADD_MODEL_ENGINE_ASSOCIATION_FAILED';


export const ADD_MODEL_DRIVE_ASSOCIATION: 'ADD_MODEL_DRIVE_ASSOCIATION' = 'ADD_MODEL_DRIVE_ASSOCIATION';
export const ADD_MODEL_DRIVE_ASSOCIATION_SUCCEED: 'ADD_MODEL_DRIVE_ASSOCIATION_SUCCEED' = 'ADD_MODEL_DRIVE_ASSOCIATION_SUCCEED';
export const ADD_MODEL_DRIVE_ASSOCIATION_FAILED: 'ADD_MODEL_DRIVE_ASSOCIATION_FAILED' = 'ADD_MODEL_DRIVE_ASSOCIATION_FAILED';

export const ADD_MODEL_BODY_TYPE_ASSOCIATION: 'ADD_MODEL_BODY_TYPE_ASSOCIATION' = 'ADD_MODEL_BODY_TYPE_ASSOCIATION';
export const ADD_MODEL_BODY_TYPE_ASSOCIATION_SUCCEED: 'ADD_MODEL_BODY_TYPE_ASSOCIATION_SUCCEED' = 'ADD_MODEL_BODY_TYPE_ASSOCIATION_SUCCEED';
export const ADD_MODEL_BODY_TYPE_ASSOCIATION_FAILED: 'ADD_MODEL_BODY_TYPE_ASSOCIATION_FAILED' = 'ADD_MODEL_BODY_TYPE_ASSOCIATION_FAILED';

export const ADD_MODEL_TRANSMISSION_ASSOCIATION: 'ADD_MODEL_TRANSMISSION_ASSOCIATION' = 'ADD_MODEL_TRANSMISSION_ASSOCIATION';
export const ADD_MODEL_TRANSMISSION_ASSOCIATION_SUCCEED: 'ADD_MODEL_TRANSMISSION_ASSOCIATION_SUCCEED' = 'ADD_MODEL_TRANSMISSION_ASSOCIATION_SUCCEED';
export const ADD_MODEL_TRANSMISSION_ASSOCIATION_FAILED: 'ADD_MODEL_TRANSMISSION_ASSOCIATION_SUCCEED' = 'ADD_MODEL_TRANSMISSION_ASSOCIATION_SUCCEED';

export const ADD_MODEL_COLOR_ASSOCIATION: 'ADD_MODEL_COLOR_ASSOCIATION' = 'ADD_MODEL_COLOR_ASSOCIATION';
export const ADD_MODEL_COLOR_ASSOCIATION_SUCCEED: 'ADD_MODEL_COLOR_ASSOCIATION_SUCCEED' = 'ADD_MODEL_COLOR_ASSOCIATION_SUCCEED';
export const ADD_MODEL_COLOR_ASSOCIATION_FAILED: 'ADD_MODEL_COLOR_ASSOCIATION_FAILED' = 'ADD_MODEL_COLOR_ASSOCIATION_FAILED';