import {IListingResponse} from "../../type/listings/listings";

export const ADD_LISTING_REQUEST: 'ADD_LISTING_REQUEST' = 'ADD_LISTING_REQUEST';
export const ADD_LISTING_SUCCESS: 'ADD_LISTING_SUCCESS' = 'ADD_LISTING_SUCCESS';
export const ADD_LISTING_FAILURE: 'ADD_LISTING_FAILURE' = 'ADD_LISTING_FAILURE';


export const GET_ENGINES_BY_MODEL: 'GET_ENGINES_BY_MODEL' = 'GET_ENGINES_BY_MODEL';
export const GET_ENGINES_BY_MODEL_SUCCEED: 'GET_ENGINES_BY_MODEL_SUCCEED' = 'GET_ENGINES_BY_MODEL_SUCCEED';
export const GET_ENGINES_BY_MODEL_FAILED: 'GET_ENGINES_BY_MODEL_FAILED' = 'GET_ENGINES_BY_MODEL_FAILED';

export const GET_TRANSMISSIONS_BY_MODEL: 'GET_TRANSMISSIONS_BY_MODEL' = 'GET_TRANSMISSIONS_BY_MODEL';
export const GET_TRANSMISSIONS_BY_MODEL_SUCCEED: 'GET_TRANSMISSIONS_BY_MODEL_SUCCEED' = 'GET_TRANSMISSIONS_BY_MODEL_SUCCEED';
export const GET_TRANSMISSIONS_BY_MODEL_FAILED: 'GET_TRANSMISSIONS_BY_MODEL_FAILED' = 'GET_TRANSMISSIONS_BY_MODEL_FAILED';

export const GET_DRIVES_BY_MODEL: 'GET_DRIVES_BY_MODEL' = 'GET_DRIVES_BY_MODEL';
export const GET_DRIVES_BY_MODEL_SUCCEED: 'GET_DRIVES_BY_MODEL_SUCCEED' = 'GET_DRIVES_BY_MODEL_SUCCEED';
export const GET_DRIVES_BY_MODEL_FAILED: 'GET_DRIVES_BY_MODEL_FAILED' = 'GET_DRIVES_BY_MODEL_FAILED';

export const GET_COLORS_BY_MODEL: 'GET_COLORS_BY_MODEL' = 'GET_COLORS_BY_MODEL';
export const GET_COLORS_BY_MODEL_SUCCEED: 'GET_COLORS_BY_MODEL_SUCCEED' = 'GET_COLORS_BY_MODEL_SUCCEED';
export const GET_COLORS_BY_MODEL_FAILED: 'GET_COLORS_BY_MODEL_FAILED' = 'GET_COLORS_BY_MODEL_FAILED';

export const GET_BODYTYPES_BY_MODEL: 'GET_BODYTYPES_BY_MODEL' = 'GET_BODYTYPES_BY_MODEL';
export const GET_BODYTYPES_BY_MODEL_SUCCEED: 'GET_BODYTYPES_BY_MODEL_SUCCEED' = 'GET_BODYTYPES_BY_MODEL_SUCCEED';
export const GET_BODYTYPES_BRAND_FAILED: 'GET_BODYTYPES_BRAND_FAILED' = 'GET_BODYTYPES_BRAND_FAILED';

export const SET_ACTIVE_MODEL: 'SET_ACTIVE_MODEL' = 'SET_ACTIVE_MODEL';
export const SET_ACTIVE_BRAND = 'SET_ACTIVE_BRAND';
export const SET_ACTIVE_DRIVE = 'SET_ACTIVE_DRIVE';
export const SET_ACTIVE_ENGINE = 'SET_ACTIVE_ENGINE';
export const SET_ACTIVE_BODYTYPE = 'SET_ACTIVE_BODYTYPE';
export const SET_ACTIVE_COLOR = 'SET_ACTIVE_COLOR';
export const SET_ACTIVE_TRANSMISSION = 'SET_ACTIVE_TRANSMISSION';
export const SET_ACTIVE_PRICE = 'SET_ACTIVE_PRICE';
export const SET_ACTIVE_MILEAGE = 'SET_ACTIVE_MILEAGE';
export const SET_ACTIVE_PHOTOS = 'SET_ACTIVE_PHOTOS';
export const SET_ACTIVE_PLACE = 'SET_ACTIVE_PLACE';
export const SET_ACTIVE_YEAR = 'SET_ACTIVE_YEAR';
export const SET_ACTIVE_VIN = 'SET_ACTIVE_VIN';
export const SET_ACTIVE_OWNERSCOUNT = 'SET_ACTIVE_OWNERSCOUNT';
export const SET_ACTIVE_EXCHANGE = 'SET_ACTIVE_EXCHANGE';
export const SET_ACTIVE_DESCRIPTION = 'SET_ACTIVE_DESCRIPTION';
export const SET_ACTIVE_PTS = 'SET_ACTIVE_PTS';



export const addListingRequest = () => ({
    type: ADD_LISTING_REQUEST,
});

export const addListingSuccess = (listing: IListingResponse) => ({
    type: ADD_LISTING_SUCCESS,
    payload: listing,
});

export const addListingFailure = (error: any) => ({
    type: ADD_LISTING_FAILURE,
    payload: error,
});