
export const GET_LISTINGS: 'GET_LISTINGS' = 'GET_LISTINGS';
export const GET_LISTINGS_SUCCESS: 'GET_LISTINGS_SUCCESS' = 'GET_LISTINGS_SUCCESS';
export const GET_LISTINGS_FAILURE: 'GET_LISTINGS_FAILURE' = 'GET_LISTINGS_FAILURE';


export const UPDATE_SEARCH_PARAMETERS: 'UPDATE_SEARCH_PARAMETERS' = 'UPDATE_SEARCH_PARAMETERS';

export const SET_ACTIVE_TAB: 'SET_ACTIVE_TAB' = 'SET_ACTIVE_TAB';
export const RESET_MODELS_BY_BRAND: 'RESET_MODELS_BY_BRAND' = 'RESET_MODELS_BY_BRAND';



export const GET_BRANDS_LISTINGS: 'GET_BRANDS_LISTINGS' = 'GET_BRANDS_LISTINGS';
export const GET_BRANDS_LISTINGS_SUCCEED: 'GET_BRANDS_LISTINGS_SUCCEED' = 'GET_BRANDS_LISTINGS_SUCCEED';
export const GET_BRANDS_LISTINGS_FAILED: 'GET_BRANDS_LISTINGS_FAILED' = 'GET_BRANDS_LISTINGS_FAILED';

export const GET_MODELS_BY_BRAND_LISTINGS: 'GET_MODELS_BY_BRAND_LISTINGS' = 'GET_MODELS_BY_BRAND_LISTINGS';
export const GET_MODELS_BY_BRAND_LISTINGS_SUCCEED: 'GET_MODELS_BY_BRAND_LISTINGS_SUCCEED' = 'GET_MODELS_BY_BRAND_LISTINGS_SUCCEED';
export const GET_MODELS_BY_BRAND_LISTINGS_FAILED: 'GET_MODELS_BY_BRAND_LISTINGS_FAILED' = 'GET_MODELS_BY_BRAND_LISTINGS_FAILED';

export const GET_ENGINES_BY_MODEL_LISTINGS: 'GET_ENGINES_BY_MODEL_LISTINGS' = 'GET_ENGINES_BY_MODEL_LISTINGS';
export const GET_ENGINES_BY_MODEL_LISTINGS_SUCCEED: 'GET_ENGINES_BY_MODEL_LISTINGS_SUCCEED' = 'GET_ENGINES_BY_MODEL_LISTINGS_SUCCEED';
export const GET_ENGINES_BY_MODEL_LISTINGS_FAILED: 'GET_ENGINES_BY_MODEL_LISTINGS_FAILED' = 'GET_ENGINES_BY_MODEL_LISTINGS_FAILED';

export const GET_TRANSMISSIONS_BY_MODEL_LISTINGS: 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS' = 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS';
export const GET_TRANSMISSIONS_BY_MODEL_LISTINGS_SUCCEED: 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS_SUCCEED' = 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS_SUCCEED';
export const GET_TRANSMISSIONS_BY_MODEL_LISTINGS_FAILED: 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS_FAILED' = 'GET_TRANSMISSIONS_BY_MODEL_LISTINGS_FAILED';

export const GET_DRIVES_BY_MODEL_LISTINGS: 'GET_DRIVES_BY_MODEL_LISTINGS' = 'GET_DRIVES_BY_MODEL_LISTINGS';
export const GET_DRIVES_BY_MODEL_LISTINGS_SUCCEED: 'GET_DRIVES_BY_MODEL_LISTINGS_SUCCEED' = 'GET_DRIVES_BY_MODEL_LISTINGS_SUCCEED';
export const GET_DRIVES_BY_MODEL_LISTINGS_FAILED: 'GET_DRIVES_BY_MODEL_LISTINGS_FAILED' = 'GET_DRIVES_BY_MODEL_LISTINGS_FAILED';

export const GET_COLORS_BY_MODEL_LISTINGS: 'GET_COLORS_BY_MODEL_LISTINGS' = 'GET_COLORS_BY_MODEL_LISTINGS';
export const GET_COLORS_BY_MODEL_LISTINGS_SUCCEED: 'GET_COLORS_BY_MODEL_LISTINGS_SUCCEED' = 'GET_COLORS_BY_MODEL_LISTINGS_SUCCEED';
export const GET_COLORS_BY_MODEL_LISTINGS_FAILED: 'GET_COLORS_BY_MODEL_LISTINGS_FAILED' = 'GET_COLORS_BY_MODEL_LISTINGS_FAILED';

export const GET_BODYTYPES_BY_MODEL_LISTINGS: 'GET_BODYTYPES_BY_MODEL_LISTINGS' = 'GET_BODYTYPES_BY_MODEL_LISTINGS';
export const GET_BODYTYPES_BY_MODEL_LISTINGS_SUCCEED: 'GET_BODYTYPES_BY_MODEL_LISTINGS_SUCCEED' = 'GET_BODYTYPES_BY_MODEL_LISTINGS_SUCCEED';
export const GET_BODYTYPES_BY_MODEL_LISTINGS_FAILED: 'GET_BODYTYPES_BY_MODEL_LISTINGS_FAILED' = 'GET_BODYTYPES_BY_MODEL_LISTINGS_FAILED';
